### ISSUE TITLE
Parameter fontSize causes widget to crash

### ISSUE THREAD

**Issue by gseront** [ketanchoyal/mapbox_search_flutter#18]
Parameter fontSize of MapBoxPlaceSearchWidget is a String but is used in a context where a double is expected.
This causes a crash of the widget if the parameter is used:

type 'String' is not a subtype of type 'double?'

When the exception was thrown, this was the stack: 
#0      _MapBoxPlaceSearchWidgetState._searchInput (package:mapbox_search_flutter/src/map_box_place_search_widget.dart:160:37)
#1      _MapBoxPlaceSearchWidgetState.build (package:mapbox_search_flutter/src/map_box_place_search_widget.dart:110:18)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4792:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4847:11)
...

**Comment by gseront** [comment]
I'd happy to correct it myself (I already did it in my own project) if you give me access.
