### ISSUE TITLE
_MapBoxPlaceSearchWidgetState.dispose 

### ISSUE THREAD

**Issue by devzom** [ketanchoyal/mapbox_search_flutter#3]
Hey, there is a issue with canceling rebuiliding.

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while finalizing the widget tree:
The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _MapBoxPlaceSearchWidgetState.dispose (package:mapbox_search_flutter/src/map_box_place_search_widget.dart:106:20)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4733:12)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by ketanchoyal** [comment]
Thanks, will look into it asap

**Comment by devzom** [comment]
OKey, thank You in advance :) 

I have some other error atm:

```
W/IInputConnectionWrapper(26521): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(26521): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(26521): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(26521): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(26521): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(26521): getTextBeforeCursor on inactive InputConnection
E/SpannableStringBuilder(26521): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/chatty  (26521): uid=10326(com.mobiqe.mobiqe_v1) identical 2 lines
E/SpannableStringBuilder(26521): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26521): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26521): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/flutter (26521): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() callback argument returned a Future.
E/flutter (26521): The setState() method on _MapBoxPlaceSearchWidgetState#71066(ticker inactive) was called with a closure or method that returned a Future. Maybe it is marked as "async".
E/flutter (26521): Instead of performing asynchronous work inside a call to setState(), first execute the work (without updating the widget state), and then synchronously update the state inside a call to setState().
E/flutter (26521): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1236:9)
E/flutter (26521): #1      State.setState (package:flutter/src/widgets/framework.dart:1252:6)
E/flutter (26521): #2      _MapBoxPlaceSearchWidgetState._searchInput.<anonymous closure>.<anonymous closure> (package:mapbox_search_flutter/src/map_box_place_search_widget.dart:170:21)
E/flutter (26521): #3      _rootRun (dart:async/zone.dart:1180:38)
E/flutter (26521): #4      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (26521): #5      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (26521): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (26521): #7      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (26521): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (26521): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (26521): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (26521): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (26521): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (26521): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (26521): 

```
