### ISSUE TITLE
The following NoSuchMethodError was thrown while finalizing the widget tree: The method 'cancel' was called on null.

### ISSUE THREAD

**Issue by devzom** [ketanchoyal/mapbox_search_flutter#5]
Hey, I found an issue which exist when I'm opening a separate window with search_bar, don't search for anything and close the page with `   Navigator.pop(context);`

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while finalizing the widget tree:
The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _MapBoxPlaceSearchWidgetState.dispose (package:mapbox_search_flutter/src/map_box_place_search_widget.dart:106:20)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4738:12)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1927:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1925:7)
...
═════════════════════════════════════════════════════════════

```

**Comment by dariotrombello** [comment]
Got the same error. https://github.com/ketanchoyal/mapbox_search_flutter/pull/6 will fix it.

**Comment by ketanchoyal** [comment]
issue fixed by @dariotrombello
